import { ORDER_STATUS_LABELS } from "../constants";

export const STATUS_COLORS = {
  [ORDER_STATUS_LABELS.WAITING]: '#FF00EE',
  [ORDER_STATUS_LABELS.PRODUCTION]: '#FFBB00',
  [ORDER_STATUS_LABELS.DELIVERED]: '#3FDAD2',
};